

server:
  port: 9099

spring:
  application:
    name: mobiliz-user-vehicle-tree-shape-service
  main:
    allow-circular-references: true
  security:
    user:
      password: none
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mypassword


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

