server:
  port: 9091

spring:
  application:
    name: mobiliz-authentication-service

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/mobiliz
    username: postgres
    password: mypassword


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/